[build]
  base = "web"
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://edubrazil-kehra.netlify.app"

[functions]
  directory = "netlify/functions"

[[schedule]]
  interval = "@daily"
  function = "send-reminders"
